### ISSUE TITLE
Login Page stuck on loading when error is caught

### ISSUE THREAD

**Issue by JackZhao98** [cs188-software-design-security-w20/routine-machine#94]
Login page button stuck in loading widget when a firebase auth is unsuccessful or interrupted:
1. Wrong username / password (Can't hit sign in again and error prompt is not shown (if there is one))
2. Interrupted Sign in with Apple (tap on the button, an iOS prompt pops out, if dismiss the view, sign in with apple button does not return to original state, stuck in loading loop)

**Comment by carinaimy** [comment]
I just fixed the first one with the wrong username/password. For the second one, I need to check the sign in with apple part and see how it can be fixed.
